#!/bin/sh
# Copyright 2025 Luka Kladarić, Chaos Guru
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

echo "Rebuilding SSH keys"

echo "# authorized_keys is auto-generated by the docker-entrypoint.sh script" > /home/dev/.ssh/authorized_keys

for user in $(cat /home/dev/authorized_users); do
  echo "# Keys for user ${user} begin here" >> /home/dev/.ssh/authorized_keys
  wget -q https://github.com/${user}.keys -O - >> /home/dev/.ssh/authorized_keys
done

cat /home/dev/.ssh/authorized_keys

exec "$@"
