#!/bin/sh

echo "Rebuilding SSH keys"

echo "# authorized_keys is auto-generated by the docker-entrypoint.sh script" > /home/dev/.ssh/authorized_keys

for user in $(cat /home/dev/authorized_users); do
  echo "# Keys for user ${user} begin here" >> /home/dev/.ssh/authorized_keys
  wget -q https://github.com/${user}.keys -O - >> /home/dev/.ssh/authorized_keys
done

cat /home/dev/.ssh/authorized_keys

exec "$@"
